### PR TITLE
Change default target to avoid installation.

### LINKED ISSUE #20: Build system tries to create a file on the system during the build step
```
$ make PREFIX=/usr
make -C fasm-plugin test
make -C xdc-plugin test
make[1]: Entering directory '/home/anubis/git/symbiflow-arch-pkgs/yosys-symbiflow-plugins-git/src/yosys-symbiflow-plugins/fasm-plugin'
make[1]: Entering directory '/home/anubis/git/symbiflow-arch-pkgs/yosys-symbiflow-plugins-git/src/yosys-symbiflow-plugins/xdc-plugin'
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -ggdb -I/usr/share/yosys/include -MD -D_YOSYS_ -fPIC -I/usr/include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER -D_FORTIFY_SOURCE=2  -c -o fasm.o fasm.cc
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -ggdb -I/usr/share/yosys/include -MD -D_YOSYS_ -fPIC -I/usr/include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_ZLIB -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER -D_FORTIFY_SOURCE=2  -c -o xdc.o xdc.cc
mkdir -p /usr/share/yosys/plugins/fasm_extra_modules/
mkdir: cannot create directory ‘/usr/share/yosys/plugins’: Permission denied
make[1]: *** [Makefile:18: install_modules] Error 1
make[1]: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by litghost**
Fixes #20

FYI @FFY00

### CODE REVIEW

**Comment by FFY00** [comment]
The makefile still tries to create `/usr/share/yosys/plugins` during build, which should only happen in `install`.

```
make -C fasm-plugin test
make -C xdc-plugin test
make[1]: Entering directory '/build/yosys-symbiflow-plugins-git/src/yosys-symbiflow-plugins/fasm-plugin'
make[1]: Entering directory '/build/yosys-symbiflow-plugins-git/src/yosys-symbiflow-plugins/xdc-plugin'
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -ggdb -I/usr/share/yosys/include -MD -D_YOSYS_ -fPIC -I/usr/include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER -D_FORTIFY_SOURCE=2  -c -o xdc.o xdc.cc
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -ggdb -I/usr/share/yosys/include -MD -D_YOSYS_ -fPIC -I/usr/include -std=c++11 -Os -DYOSYS_ENABLE_READLINE -DYOSYS_ENABLE_PLUGINS -DYOSYS_ENABLE_GLOB -DYOSYS_ENABLE_TCL -DYOSYS_ENABLE_ABC -DYOSYS_ENABLE_COVER -D_FORTIFY_SOURCE=2  -c -o fasm.o fasm.cc
mkdir -p /usr/share/yosys/plugins/fasm_extra_modules/
mkdir: cannot create directory ‘/usr/share/yosys/plugins’: Permission denied
```

**Comment by FFY00** [comment]
Seems to be fixed now, thanks :smile:.

However, I hit a different issue.

```
ERROR: Can't load module `./xdc': /usr/bin/../share/yosys/plugins/xdc.so: cannot open shared object file: No such file or directory
```

I tried with the latest yosys release and from git. Should I open a different issue for this?

**Comment by litghost** [comment]
> Seems to be fixed now, thanks .
> 
> However, I hit a different issue.
> 
> ```
> ERROR: Can't load module `./xdc': /usr/bin/../share/yosys/plugins/xdc.so: cannot open shared object file: No such file or directory
> ```
> 
> I tried with the latest yosys release and from git. Should I open a different issue for this?

Can you check the permissions on that file?  Is it not marked are readable for all?  I'd guess that the install step isn't setting permissions correctly.

**Comment by FFY00** [comment]
There is no file. Do I need to enable something in yosys?

This is how I'm building:
https://github.com/FFY00/symbiflow-arch-pkgs/blob/master/yosys-git/PKGBUILD#L38

**Comment by litghost** [comment]
> There is no file. Do I need to enable something in yosys?

This project builds those file (`xdc.so` and `fasm.so`). In order for the tests from this project to run, the plugins need to be installed to relevant yosys directory (`/usr/bin/../share/yosys/plugins/`).  The install target in this project will put `xdc.so` and `fasm.so` in the directory specified by `yosys-config`.

**Comment by FFY00** [comment]
Ah sorry. Can't we make the tests run in-tree? When packaging, I can't install anything to the system.

**Comment by litghost** [comment]
For context, yosys supports a dynamic plugin system, and by default finds those plugins in the yosys share path.  This project builds two plugins for yosys, and provides a target (`install`) that copies the files to the path supplied from `yosys-config`.  In order for yosys to find them in the expected place, something needs to put them there.  That can be a `Makefile` in the case of a development system, or some other package manager in other cases.

**Comment by FFY00** [comment]
This make sense. Do you know if there's any to get yosys to look in other place?

**Comment by litghost** [comment]
> This make sense. Do you know if there's any to get yosys to look in other place?

The documentation makes me wonder if an absolute path would be accepted.  If an absolute path is not accepted, a yosys change would be required to support what you ask.

**Comment by FFY00** [comment]
Anyway, this can be merged. I still have one issue, `DESTDIR` is not being respected.

https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Pull request merged**
