### PR TITLE
Modified ffs map file

### PR DESCRIPTION
**Pull request by rakeshm75**
Signed-off-by: rakeshm <rakeshm@quicklogic.com>

### CODE REVIEW

**Comment by rakeshm75** [comment]
@tara, please review

**Comment by rakeshm75** [comment]
In designs that have a signal that sets and resets flops, like a 8-bit counter with a reset value = 8'hA5, it was putting individual FF into set and reset together. It was not tying off (to VCC) either reset or set which is not used. In above counter, bit[0] flop set need to be connected to active signal and reset needs to be tied off to VCC (disable). So I made the changes in the ffs_map.v file such that when dffs is inferred the reset port is tied to 1'b1 (disabled) & when dffr is inferred the set port is tied to 1'b1 (disabled) .

**Comment by tpagarani** [comment]
LGTM. @kgugala could you please review and merge it.

**Comment by tpagarani** [comment]
@rakeshm75, CI is failing on ff test cases. I think you need to change them as now dffs and dffr is repalced by dffsr

**Comment by tpagarani** [comment]
@rakeshm75, have you updated the tests to correct CI failures?

**Comment by tpagarani** [comment]
@kgugala, @mkurc-ant Kindly review and merge

**Review by mkurc-ant — APPROVED** [review]
LGTM

**Comment by tpagarani** [comment]
@mkurc-ant when this can be merged?

**Pull request merged**
