### PR TITLE
add dffsr support

### PR DESCRIPTION
**Pull request by tpagarani**
Since the DFF supports both async set and reset, added support for DFFSR primitive 

Signed-off-by: Tarachand Pagarani <tpagarani@quicklogic.com>

### CODE REVIEW

**Comment by tpagarani** [comment]
@kgugala, kindly help review and merge this PR.

**Comment by mithro** [comment]
The CI appears to be failing?

**Review by mkurc-ant — APPROVED** [review]
LGTM.

The CI failure looks strange as it crashed during Yosys build. I've restarted it.

**Comment by tpagarani** [comment]
> LGTM.
> 
> The CI failure looks strange as it crashed during Yosys build. I've restarted it.

CI continues to fail during Yosys build. Any idea what's going wrong?

**Comment by mkurc-ant** [comment]
I'm investigating that. I've opened a second WIP PR to debug the CI.

**Comment by mkurc-ant** [comment]
Attempt to fix the Yosys build issue: https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/109

**Comment by mkurc-ant** [comment]
@tpagarani Can you please rebase this PR on top of the current master? A fix for the CI has just been pushed there.

**Comment by mkurc-ant** [comment]
@tpagarani I must have accidentally pushed the master branch from SymbiFlow to your fork which made GH close this PR. But no worries, I have rebased your changes regarding DFFSR support onto the upstream master and created a new PR: #110

**Pull request closed without merging**
